<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MQTT" Id="{22a2f25d-52ae-4956-8afe-fe8eb2daff36}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MQTT
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MQTT">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>